Repository micronaut-projects/micronaut-rabbitmq, pull requests merged in 2020-09, with the labels that each got.

#126 [rabbitmq] Update common files for branch master
  .github/workflows/release-notes.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#130 doc: link to github releases
  src/main/docs/guide/toc.yml
  src/main/docs/guide/whatsNew.adoc
Labels: type: docs

#131 ci: set github core branch to 2.0.x
  gradle.properties
Labels: relates-to: build

#127 [rabbitmq] Update common files for branch 1.2.x
  .github/workflows/release-notes.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#134 ci: set github core to 2.1.x
  gradle.properties
Labels: relates-to: build

#135 ci: set kotlin version to 1.4.0
  gradle.properties
Labels: lang: kotlin, type: dependency-upgrade

#141 [rabbitmq] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#139 Dependency upgrades
  build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#142 [rabbitmq] Update common files for branch 2.0.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#143 Set micronaut test to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade
