Repository micronaut-projects/micronaut-rabbitmq, pull requests merged in 2022-10, with the labels that each got.

#372 ci: SLSA provenance
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#386 doc: extract rpc sections
  src/main/docs/guide/rpc.adoc
  src/main/docs/guide/rpc/rpcClientSide.adoc
  src/main/docs/guide/rpc/rpcConfiguration.adoc
  src/main/docs/guide/rpc/rpcServerSide.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#395 Issue-325 Support consumer auto acknowledge mode
  gradle.properties
  rabbitmq/src/main/java/io/micronaut/rabbitmq/annotation/Queue.java
  rabbitmq/src/main/java/io/micronaut/rabbitmq/bind/AcknowledgementBinder.java
  rabbitmq/src/main/java/io/micronaut/rabbitmq/bind/AcknowledgmentAction.java
  rabbitmq/src/main/java/io/micronaut/rabbitmq/bind/RabbitMessageCloseable.java
  rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java
  rabbitmq/src/test/groovy/io/micronaut/rabbitmq/annotation/QueueAnnotationSpec.groovy
  src/main/docs/guide/consumer/consumerMethods/consumerAcknowledge.adoc
Labels: type: enhancement
