Repository micronaut-projects/micronaut-rabbitmq, pull requests merged in 2023-05, with the labels that each got.

#457 Document breaking change and fix missing code examples.
  src/main/docs/guide/config.adoc
  src/main/docs/guide/consumer/consumerMethods/consumerAcknowledge.adoc
  src/main/docs/guide/consumer/consumerMethods/consumerParameters/consumerCustom.adoc
  src/main/docs/guide/consumer/consumerMethods/consumerParameters/consumerHeaders.adoc
  src/main/docs/guide/consumer/consumerMethods/consumerParameters/consumerProperties.adoc
  src/main/docs/guide/consumer/consumerMethods/consumerParameters/consumerQueue.adoc
  src/main/docs/guide/consumer/consumerMethods/consumerParameters/consumerTypes.adoc
  src/main/docs/guide/initialization.adoc
  src/main/docs/guide/producer.adoc
  src/main/docs/guide/producer/producerMethods/producerAcknowledge.adoc
  src/main/docs/guide/producer/producerMethods/producerParameters/producerBinding.adoc
  src/main/docs/guide/producer/producerMethods/producerParameters/producerHeaders.adoc
  src/main/docs/guide/producer/producerMethods/producerParameters/producerProperties.adoc
  src/main/docs/guide/quickStart.adoc
  src/main/docs/guide/rpc/rpcClientSide.adoc
  src/main/docs/guide/rpc/rpcServerSide.adoc
  src/main/docs/guide/serdes/custom.adoc
  src/main/docs/guide/whatsNew.adoc
Labels: type: docs

#463 [rabbitmq] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#465 RabbiMQ to M5
  build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.rabbitmq-base.gradle
  gradle.properties
  gradle/libs.versions.toml
  rabbitmq/build.gradle
  settings.gradle
Labels: type: dependency-upgrade

#467 [rabbitmq] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build
