Repository micronaut-projects/micronaut-rabbitmq, pull requests merged in 2023-08, with the labels that each got.

#512 depend on json core not serde
  rabbitmq/build.gradle
  rabbitmq/build.gradle.kts
  rabbitmq/src/main/java/io/micronaut/rabbitmq/serdes/JsonRabbitMessageSerDes.java
  settings.gradle
Labels: relates-to: build, type: bug

#517 [rabbitmq] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#514 Infinite Loop When Channels Leak
  rabbitmq/src/main/java/io/micronaut/rabbitmq/connect/DefaultChannelPool.java
  rabbitmq/src/test/groovy/io/micronaut/rabbitmq/connect/DefaultChannelPoolSpec.groovy
Labels: type: bug

#518 [rabbitmq] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#515 Send application events before/after RabbitMQ consumer subscribe to a queue
  docs-examples/example-groovy/src/test/groovy/io/micronaut/rabbitmq/docs/event/MyStartedEventListener.groovy
  docs-examples/example-groovy/src/test/groovy/io/micronaut/rabbitmq/docs/event/MyStartingEventListener.groovy
  docs-examples/example-java/src/test/java/io/micronaut/rabbitmq/docs/event/MyStartedEventListener.java
  docs-examples/example-java/src/test/java/io/micronaut/rabbitmq/docs/event/MyStartingEventListener.java
  docs-examples/example-kotlin/src/test/kotlin/io/micronaut/rabbitmq/docs/event/MyStartedEventListener.kt
  docs-examples/example-kotlin/src/test/kotlin/io/micronaut/rabbitmq/docs/event/MyStartingEventListener.kt
  rabbitmq/src/main/java/io/micronaut/rabbitmq/event/AbstractRabbitConsumerEvent.java
  rabbitmq/src/main/java/io/micronaut/rabbitmq/event/AbstractRabbitEvent.java
  rabbitmq/src/main/java/io/micronaut/rabbitmq/event/RabbitConsumerStarted.java
  rabbitmq/src/main/java/io/micronaut/rabbitmq/event/RabbitConsumerStarting.java
  rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java
  rabbitmq/src/test/groovy/io/micronaut/rabbitmq/event/RabbitListenerEventsSpec.groovy
  src/main/docs/guide/consumer/consumerEvents.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement

#508 Add support for AMQP "mandatory" flag
  docs-examples/example-groovy/src/test/groovy/io/micronaut/rabbitmq/docs/parameters/MandatoryProductClient.groovy
  docs-examples/example-groovy/src/test/groovy/io/micronaut/rabbitmq/docs/parameters/MyReturnListener.groovy
  docs-examples/example-java/src/test/java/io/micronaut/rabbitmq/docs/parameters/MandatoryProductClient.java
  docs-examples/example-java/src/test/java/io/micronaut/rabbitmq/docs/parameters/MyReturnListener.java
  docs-examples/example-kotlin/src/test/kotlin/io/micronaut/rabbitmq/docs/parameters/MandatoryProductClient.kt
  docs-examples/example-kotlin/src/test/kotlin/io/micronaut/rabbitmq/docs/parameters/MyReturnListener.kt
  rabbitmq/src/main/java/io/micronaut/rabbitmq/annotation/Mandatory.java
  rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQIntroductionAdvice.java
  rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/StaticPublisherState.java
  rabbitmq/src/main/java/io/micronaut/rabbitmq/reactive/RabbitPublishState.java
  rabbitmq/src/main/java/io/micronaut/rabbitmq/reactive/ReactorReactivePublisher.java
  rabbitmq/src/test/groovy/io/micronaut/rabbitmq/annotation/MandatorySpec.groovy
  rabbitmq/src/test/groovy/io/micronaut/rabbitmq/connect/ChannelPoolListener.groovy
  rabbitmq/src/test/groovy/io/micronaut/rabbitmq/connect/ReactiveChannelSpec.groovy
  src/main/docs/guide/producer/producerMethods/producerParameters/producerMandatory.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement
